spring.application.name=curdDTOSpringBootDemo
spring.datasource.url=jdbc:mysql://localhost:3306/crudDTO
spring.datasource.username=root
spring.datasource.password=Pass@123
spring.jpa.hibernate.ddl-auto=update